[package]
name = "prayer-times"
version = "0.1.0"
authors = ["Ilyas Turki <turki.ilyass@gmail.com>"]
edition = "2021"
description = "Islamic Prayer Times Notification"
readme = "README.md"
homepage = "https://github.com/Yasso9/prayer-times"
repository = "https://github.com/Yasso9/prayer-times"
license = "MIT"
exclude = ["/.vscode/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.14", features = ["derive"] }
notify-rust = "4.10.0"
strum = "0.25.0"
strum_macros = "0.25.3"
