[package]
name = "prayer-time"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
islam = "3.2.0"
notify-rust = "4.10.0"
